package bloom

import (
	"github.com/liyue201/gostl/ds/bitmap"
	"github.com/liyue201/gostl/utils/sync"
)

const salt = "g9hmj2fhgr"

var defaultLocker sync.FakeLocker

// Options holds BloomFilter's options
type Options struct {
	locker sync.Locker
}

// Option is a function type used to set Options
type Option func(opt *Options)

// WithGoroutineSafe is used to config a BloomFilter with goroutine-safe
func WithGoroutineSafe() Option { _ = "STUB: not implemented"; return *new(Option) }

// BloomFilter is an implementation of bloom filter
type BloomFilter struct {
	m      uint64
	k      uint64
	b      *bitmap.Bitmap
	locker sync.Locker
}

// New creates a new BloomFilter with m bits and k hash functions
func New(m, k uint64, opts ...Option) *BloomFilter { _ = "STUB: not implemented"; return nil }

// NewWithEstimates creates a new BloomFilter with n and fp.
// n is the capacity of the BloomFilter
// fp is the tolerated error rate of the BloomFilter
func NewWithEstimates(n uint64, fp float64, opts ...Option) *BloomFilter {
	_ = "STUB: not implemented"
	return nil
}

// NewFromData creates a new BloomFilter from data generated by function 'Data()'
func NewFromData(data []byte, opts ...Option) *BloomFilter { _ = "STUB: not implemented"; return nil }

// EstimateParameters estimates m and k from n and p
func EstimateParameters(n uint64, p float64) (m uint64, k uint64) {
	_ = "STUB: not implemented"
	return 0, 0
}

// Add adds val to the BloomFilter
func (bf *BloomFilter) Add(val string) { _ = "STUB: not implemented"; return }

// Contains returns true if val is (high probability) in the BloomFilter, otherwise returns false.
func (bf *BloomFilter) Contains(val string) bool { _ = "STUB: not implemented"; return false }

// Data returns the data of the BloomFilter, it can bee used to creates a new BloomFilter by using function 'NewFromData' .
func (bf *BloomFilter) Data() []byte { _ = "STUB: not implemented"; return nil }
